services:
  mysql:
    image: mysql:9.1.0
    container_name: "mysql-container"
    env_file:
      - mysql.env
    networks:
      - snowhite-network
    volumes:
      - snowhite-db:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7.4.2
    container_name: "redis-container"
    networks:
      - snowhite-network
    ports:
      - "6379:6379"

  snowhite:
    image: snowhite:latest
    container_name: "snowhite-container"
    env_file:
      - .env
    networks:
      - snowhite-network
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"

networks:
  snowhite-network:
    external: true

volumes:
  snowhite-db:
    external: true